
# Global settings
[build]
  # Command to build your project
  command = "npm run build"
  # Directory to publish
  publish = "dist"
  
  # Set environment variables
  environment = { NODE_ENV = "production" }

# Redirects configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset optimization
[build.processing]
  # Minify CSS and JS files
  css = { minify = true }
  js = { minify = true }
  
# HTTP Headers configuration
[[headers]]
  # Configure headers for all files
  for = "/*"
    [headers.values]
      # Set X-Frame-Options header to deny framing
      X-Frame-Options = "DENY"
      # Enable Content Security Policy (CSP) to restrict sources
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data:; font-src 'self' data:"
      # Enable HSTS (HTTP Strict Transport Security) to enforce HTTPS
      Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
      # Prevent MIME sniffing
      X-Content-Type-Options = "nosniff"
      # Enable XSS protection
      X-XSS-Protection = "1; mode=block"
      # Prevent clickjacking
      X-Frame-Options = "DENY"
      
# Headers configuration for specific paths
[[headers]]
  for = "/images/*"
    [headers.values]
      # Set Cache-Control header to cache images for 1 year
      Cache-Control = "public, max-age=31536000"

# Rewrite rules
[[redirects]]
  # Redirect all requests to index.html for single-page applications
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  # Directory where serverless functions are stored
  directory = "functions"

# Asset optimization settings
[build.processing]
  # Optimize images
  [[build.processing.image]]
    # Optimize JPEG images
    source = "**/*.jpg"
    plugins = ["imagemin-jpegtran"]
  [[build.processing.image]]
    # Optimize PNG images
    source = "**/*.png"
    plugins = ["imagemin-optipng"]
  [[build.processing.image]]
    # Optimize SVG images
    source = "**/*.svg"
    plugins = ["imagemin-svgo"]
